/* GENERATED by tools/is1gl/protocol.py -- do not edit.
 * #included by is1gl.c, which supplies the ring writer and the
 * hand-written wrappers for the entry points that track state. */

static void emit_glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    unsigned char *r = ring_record(IS1GL_OP_glClearColor, 16);
    if (!r) return;
    put_f32(r + 0, red);
    put_f32(r + 4, green);
    put_f32(r + 8, blue);
    put_f32(r + 12, alpha);
}

void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    gl_enter();
    emit_glClearColor(red, green, blue, alpha);
    gl_leave();
}

static void emit_glClear(GLbitfield mask)
{
    unsigned char *r = ring_record(IS1GL_OP_glClear, 4);
    if (!r) return;
    put_u32(r + 0, mask);
}

void glClear(GLbitfield mask)
{
    gl_enter();
    emit_glClear(mask);
    gl_leave();
}

static void emit_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    unsigned char *r = ring_record(IS1GL_OP_glBlendFunc, 8);
    if (!r) return;
    put_u32(r + 0, sfactor);
    put_u32(r + 4, dfactor);
}

void glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    gl_enter();
    emit_glBlendFunc(sfactor, dfactor);
    gl_leave();
}

static void emit_glLineWidth(GLfloat width)
{
    unsigned char *r = ring_record(IS1GL_OP_glLineWidth, 4);
    if (!r) return;
    put_f32(r + 0, width);
}

void glLineWidth(GLfloat width)
{
    gl_enter();
    emit_glLineWidth(width);
    gl_leave();
}

static void emit_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    unsigned char *r = ring_record(IS1GL_OP_glScissor, 16);
    if (!r) return;
    put_i32(r + 0, x);
    put_i32(r + 4, y);
    put_i32(r + 8, width);
    put_i32(r + 12, height);
}

void glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    gl_enter();
    emit_glScissor(x, y, width, height);
    gl_leave();
}

static void emit_glClipPlane(GLenum plane, const GLdouble * equation)
{
    unsigned char *r = ring_record(IS1GL_OP_glClipPlane, 4 + (4) * 8);
    if (!r) return;
    put_u32(r + 0, plane);
    {
        int i_;
        for (i_ = 0; i_ < (int)(4); i_++)
            put_f64(r + 4 + i_ * 8, equation[i_]);
    }
}

void glClipPlane(GLenum plane, const GLdouble * equation)
{
    gl_enter();
    emit_glClipPlane(plane, equation);
    gl_leave();
}

static void emit_glEnable(GLenum cap)
{
    unsigned char *r = ring_record(IS1GL_OP_glEnable, 4);
    if (!r) return;
    put_u32(r + 0, cap);
}

static void emit_glDisable(GLenum cap)
{
    unsigned char *r = ring_record(IS1GL_OP_glDisable, 4);
    if (!r) return;
    put_u32(r + 0, cap);
}

static void emit_glPushAttrib(GLbitfield mask)
{
    unsigned char *r = ring_record(IS1GL_OP_glPushAttrib, 4);
    if (!r) return;
    put_u32(r + 0, mask);
}

static void emit_glPopAttrib(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glPopAttrib, 0);
    if (!r) return;
}

static void emit_glPushClientAttrib(GLbitfield mask)
{
    unsigned char *r = ring_record(IS1GL_OP_glPushClientAttrib, 4);
    if (!r) return;
    put_u32(r + 0, mask);
}

static void emit_glPopClientAttrib(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glPopClientAttrib, 0);
    if (!r) return;
}

static void emit_glMatrixMode(GLenum mode)
{
    unsigned char *r = ring_record(IS1GL_OP_glMatrixMode, 4);
    if (!r) return;
    put_u32(r + 0, mode);
}

void glMatrixMode(GLenum mode)
{
    gl_enter();
    emit_glMatrixMode(mode);
    gl_leave();
}

static void emit_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
    unsigned char *r = ring_record(IS1GL_OP_glViewport, 16);
    if (!r) return;
    put_i32(r + 0, x);
    put_i32(r + 4, y);
    put_i32(r + 8, width);
    put_i32(r + 12, height);
}

static void emit_glPushMatrix(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glPushMatrix, 0);
    if (!r) return;
}

void glPushMatrix(void)
{
    gl_enter();
    emit_glPushMatrix();
    gl_leave();
}

static void emit_glPopMatrix(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glPopMatrix, 0);
    if (!r) return;
}

void glPopMatrix(void)
{
    gl_enter();
    emit_glPopMatrix();
    gl_leave();
}

static void emit_glLoadIdentity(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glLoadIdentity, 0);
    if (!r) return;
}

void glLoadIdentity(void)
{
    gl_enter();
    emit_glLoadIdentity();
    gl_leave();
}

static void emit_glMultMatrixd(const GLdouble * m)
{
    unsigned char *r = ring_record(IS1GL_OP_glMultMatrixd, 0 + (16) * 8);
    if (!r) return;
    {
        int i_;
        for (i_ = 0; i_ < (int)(16); i_++)
            put_f64(r + 0 + i_ * 8, m[i_]);
    }
}

void glMultMatrixd(const GLdouble * m)
{
    gl_enter();
    emit_glMultMatrixd(m);
    gl_leave();
}

static void emit_glMultMatrixf(const GLfloat * m)
{
    unsigned char *r = ring_record(IS1GL_OP_glMultMatrixf, 0 + (16) * 4);
    if (!r) return;
    {
        int i_;
        for (i_ = 0; i_ < (int)(16); i_++)
            put_f32(r + 0 + i_ * 4, m[i_]);
    }
}

void glMultMatrixf(const GLfloat * m)
{
    gl_enter();
    emit_glMultMatrixf(m);
    gl_leave();
}

static void emit_glRotated(GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
{
    unsigned char *r = ring_record(IS1GL_OP_glRotated, 32);
    if (!r) return;
    put_f64(r + 0, angle);
    put_f64(r + 8, x);
    put_f64(r + 16, y);
    put_f64(r + 24, z);
}

void glRotated(GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
{
    gl_enter();
    emit_glRotated(angle, x, y, z);
    gl_leave();
}

static void emit_glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    unsigned char *r = ring_record(IS1GL_OP_glRotatef, 16);
    if (!r) return;
    put_f32(r + 0, angle);
    put_f32(r + 4, x);
    put_f32(r + 8, y);
    put_f32(r + 12, z);
}

void glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    gl_enter();
    emit_glRotatef(angle, x, y, z);
    gl_leave();
}

static void emit_glScalef(GLfloat x, GLfloat y, GLfloat z)
{
    unsigned char *r = ring_record(IS1GL_OP_glScalef, 12);
    if (!r) return;
    put_f32(r + 0, x);
    put_f32(r + 4, y);
    put_f32(r + 8, z);
}

void glScalef(GLfloat x, GLfloat y, GLfloat z)
{
    gl_enter();
    emit_glScalef(x, y, z);
    gl_leave();
}

static void emit_glTranslated(GLdouble x, GLdouble y, GLdouble z)
{
    unsigned char *r = ring_record(IS1GL_OP_glTranslated, 24);
    if (!r) return;
    put_f64(r + 0, x);
    put_f64(r + 8, y);
    put_f64(r + 16, z);
}

void glTranslated(GLdouble x, GLdouble y, GLdouble z)
{
    gl_enter();
    emit_glTranslated(x, y, z);
    gl_leave();
}

static void emit_glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
    unsigned char *r = ring_record(IS1GL_OP_glTranslatef, 12);
    if (!r) return;
    put_f32(r + 0, x);
    put_f32(r + 4, y);
    put_f32(r + 8, z);
}

void glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
    gl_enter();
    emit_glTranslatef(x, y, z);
    gl_leave();
}

static void emit_glDeleteLists(GLuint list, GLsizei range)
{
    unsigned char *r = ring_record(IS1GL_OP_glDeleteLists, 8);
    if (!r) return;
    put_u32(r + 0, list);
    put_i32(r + 4, range);
}

void glDeleteLists(GLuint list, GLsizei range)
{
    gl_enter();
    emit_glDeleteLists(list, range);
    gl_leave();
}

static void emit_glNewList(GLuint list, GLenum mode)
{
    unsigned char *r = ring_record(IS1GL_OP_glNewList, 8);
    if (!r) return;
    put_u32(r + 0, list);
    put_u32(r + 4, mode);
}

static void emit_glEndList(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glEndList, 0);
    if (!r) return;
}

static void emit_glCallList(GLuint list)
{
    unsigned char *r = ring_record(IS1GL_OP_glCallList, 4);
    if (!r) return;
    put_u32(r + 0, list);
}

static void emit_glBegin(GLenum mode)
{
    unsigned char *r = ring_record(IS1GL_OP_glBegin, 4);
    if (!r) return;
    put_u32(r + 0, mode);
}

static void emit_glEnd(void)
{
    unsigned char *r = ring_record(IS1GL_OP_glEnd, 0);
    if (!r) return;
}

static void emit_glVertex2d(GLdouble x, GLdouble y)
{
    unsigned char *r = ring_record(IS1GL_OP_glVertex2d, 16);
    if (!r) return;
    put_f64(r + 0, x);
    put_f64(r + 8, y);
}

void glVertex2d(GLdouble x, GLdouble y)
{
    gl_enter();
    emit_glVertex2d(x, y);
    gl_leave();
}

static void emit_glVertex2f(GLfloat x, GLfloat y)
{
    unsigned char *r = ring_record(IS1GL_OP_glVertex2f, 8);
    if (!r) return;
    put_f32(r + 0, x);
    put_f32(r + 4, y);
}

void glVertex2f(GLfloat x, GLfloat y)
{
    gl_enter();
    emit_glVertex2f(x, y);
    gl_leave();
}

static void emit_glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    unsigned char *r = ring_record(IS1GL_OP_glColor4f, 16);
    if (!r) return;
    put_f32(r + 0, red);
    put_f32(r + 4, green);
    put_f32(r + 8, blue);
    put_f32(r + 12, alpha);
}

static void emit_glTexCoord2f(GLfloat s, GLfloat t)
{
    unsigned char *r = ring_record(IS1GL_OP_glTexCoord2f, 8);
    if (!r) return;
    put_f32(r + 0, s);
    put_f32(r + 4, t);
}

void glTexCoord2f(GLfloat s, GLfloat t)
{
    gl_enter();
    emit_glTexCoord2f(s, t);
    gl_leave();
}

static void emit_glPixelStoref(GLenum pname, GLfloat param)
{
    unsigned char *r = ring_record(IS1GL_OP_glPixelStoref, 8);
    if (!r) return;
    put_u32(r + 0, pname);
    put_f32(r + 4, param);
}

static void emit_glPixelStorei(GLenum pname, GLint param)
{
    unsigned char *r = ring_record(IS1GL_OP_glPixelStorei, 8);
    if (!r) return;
    put_u32(r + 0, pname);
    put_i32(r + 4, param);
}

static void emit_glDrawPixels(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
{
    long img = is1gl_image_bytes(width, height, format, type);
    unsigned char *r = ring_record(IS1GL_OP_glDrawPixels, 16 + ((img + 7) & ~7L));
    if (!r) return;
    put_i32(r + 0, width);
    put_i32(r + 4, height);
    put_u32(r + 8, format);
    put_u32(r + 12, type);
    is1gl_pack_image(r + 16, pixels, width, height, format, type);
}

static void emit_glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    unsigned char *r = ring_record(IS1GL_OP_glTexEnvf, 12);
    if (!r) return;
    put_u32(r + 0, target);
    put_u32(r + 4, pname);
    put_f32(r + 8, param);
}

void glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    gl_enter();
    emit_glTexEnvf(target, pname, param);
    gl_leave();
}

static void emit_glTexEnvi(GLenum target, GLenum pname, GLint param)
{
    unsigned char *r = ring_record(IS1GL_OP_glTexEnvi, 12);
    if (!r) return;
    put_u32(r + 0, target);
    put_u32(r + 4, pname);
    put_i32(r + 8, param);
}

void glTexEnvi(GLenum target, GLenum pname, GLint param)
{
    gl_enter();
    emit_glTexEnvi(target, pname, param);
    gl_leave();
}

static void emit_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    unsigned char *r = ring_record(IS1GL_OP_glTexParameterf, 12);
    if (!r) return;
    put_u32(r + 0, target);
    put_u32(r + 4, pname);
    put_f32(r + 8, param);
}

void glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    gl_enter();
    emit_glTexParameterf(target, pname, param);
    gl_leave();
}

static void emit_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    unsigned char *r = ring_record(IS1GL_OP_glTexParameteri, 12);
    if (!r) return;
    put_u32(r + 0, target);
    put_u32(r + 4, pname);
    put_i32(r + 8, param);
}

void glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    gl_enter();
    emit_glTexParameteri(target, pname, param);
    gl_leave();
}

static void emit_glTexImage2D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
{
    long img = is1gl_image_bytes(width, height, format, type);
    unsigned char *r = ring_record(IS1GL_OP_glTexImage2D, 32 + ((img + 7) & ~7L));
    if (!r) return;
    put_u32(r + 0, target);
    put_i32(r + 4, level);
    put_i32(r + 8, internalFormat);
    put_i32(r + 12, width);
    put_i32(r + 16, height);
    put_i32(r + 20, border);
    put_u32(r + 24, format);
    put_u32(r + 28, type);
    is1gl_pack_image(r + 32, pixels, width, height, format, type);
}

static void emit_glDeleteTextures(GLsizei n, const GLuint * textures)
{
    unsigned char *r = ring_record(IS1GL_OP_glDeleteTextures, 4 + (n) * 4);
    if (!r) return;
    put_i32(r + 0, n);
    {
        int i_;
        for (i_ = 0; i_ < (int)(n); i_++)
            put_u32(r + 4 + i_ * 4, textures[i_]);
    }
}

void glDeleteTextures(GLsizei n, const GLuint * textures)
{
    gl_enter();
    emit_glDeleteTextures(n, textures);
    gl_leave();
}

static void emit_glBindTexture(GLenum target, GLuint texture)
{
    unsigned char *r = ring_record(IS1GL_OP_glBindTexture, 8);
    if (!r) return;
    put_u32(r + 0, target);
    put_u32(r + 4, texture);
}

static void emit_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
{
    long img = is1gl_image_bytes(width, height, format, type);
    unsigned char *r = ring_record(IS1GL_OP_glTexSubImage2D, 32 + ((img + 7) & ~7L));
    if (!r) return;
    put_u32(r + 0, target);
    put_i32(r + 4, level);
    put_i32(r + 8, xoffset);
    put_i32(r + 12, yoffset);
    put_i32(r + 16, width);
    put_i32(r + 20, height);
    put_u32(r + 24, format);
    put_u32(r + 28, type);
    is1gl_pack_image(r + 32, pixels, width, height, format, type);
}

static void emit_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    unsigned char *r = ring_record(IS1GL_OP_glCopyTexSubImage2D, 32);
    if (!r) return;
    put_u32(r + 0, target);
    put_i32(r + 4, level);
    put_i32(r + 8, xoffset);
    put_i32(r + 12, yoffset);
    put_i32(r + 16, x);
    put_i32(r + 20, y);
    put_i32(r + 24, width);
    put_i32(r + 28, height);
}

void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    gl_enter();
    emit_glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
    gl_leave();
}


/* ---- stubs: every entry point the application does not use.
 * This library replaces libGL rather than wrapping it, so an
 * undefined symbol here would bind to the vendor library and
 * try to reach an X server that has no context on it. Each stub
 * counts itself; a non-zero count in the report is a bug
 * report, not something to paper over at runtime. */
#define IS1GL_STUB_COUNT 496
static unsigned long is1gl_stub_hits[IS1GL_STUB_COUNT];
static const char *const is1gl_stub_names[IS1GL_STUB_COUNT] = {
    "glClearIndex",
    "glIndexMask",
    "glColorMask",
    "glAlphaFunc",
    "glLogicOp",
    "glCullFace",
    "glFrontFace",
    "glPointSize",
    "glLineStipple",
    "glPolygonMode",
    "glPolygonOffset",
    "glPolygonStipple",
    "glGetPolygonStipple",
    "glEdgeFlag",
    "glEdgeFlagv",
    "glGetClipPlane",
    "glDrawBuffer",
    "glReadBuffer",
    "glIsEnabled",
    "glEnableClientState",
    "glDisableClientState",
    "glGetBooleanv",
    "glGetDoublev",
    "glRenderMode",
    "glHint",
    "glClearDepth",
    "glDepthFunc",
    "glDepthMask",
    "glDepthRange",
    "glClearAccum",
    "glAccum",
    "glOrtho",
    "glFrustum",
    "glLoadMatrixd",
    "glLoadMatrixf",
    "glScaled",
    "glIsList",
    "glCallLists",
    "glListBase",
    "glVertex2i",
    "glVertex2s",
    "glVertex3d",
    "glVertex3f",
    "glVertex3i",
    "glVertex3s",
    "glVertex4d",
    "glVertex4f",
    "glVertex4i",
    "glVertex4s",
    "glVertex2dv",
    "glVertex2fv",
    "glVertex2iv",
    "glVertex2sv",
    "glVertex3dv",
    "glVertex3fv",
    "glVertex3iv",
    "glVertex3sv",
    "glVertex4dv",
    "glVertex4fv",
    "glVertex4iv",
    "glVertex4sv",
    "glNormal3b",
    "glNormal3d",
    "glNormal3f",
    "glNormal3i",
    "glNormal3s",
    "glNormal3bv",
    "glNormal3dv",
    "glNormal3fv",
    "glNormal3iv",
    "glNormal3sv",
    "glIndexd",
    "glIndexf",
    "glIndexi",
    "glIndexs",
    "glIndexub",
    "glIndexdv",
    "glIndexfv",
    "glIndexiv",
    "glIndexsv",
    "glIndexubv",
    "glColor3b",
    "glColor3d",
    "glColor3f",
    "glColor3i",
    "glColor3s",
    "glColor3ub",
    "glColor3ui",
    "glColor3us",
    "glColor4b",
    "glColor4d",
    "glColor4i",
    "glColor4s",
    "glColor4ub",
    "glColor4ui",
    "glColor4us",
    "glColor3bv",
    "glColor3dv",
    "glColor3fv",
    "glColor3iv",
    "glColor3sv",
    "glColor3ubv",
    "glColor3uiv",
    "glColor3usv",
    "glColor4bv",
    "glColor4dv",
    "glColor4fv",
    "glColor4iv",
    "glColor4sv",
    "glColor4ubv",
    "glColor4uiv",
    "glColor4usv",
    "glTexCoord1d",
    "glTexCoord1f",
    "glTexCoord1i",
    "glTexCoord1s",
    "glTexCoord2d",
    "glTexCoord2i",
    "glTexCoord2s",
    "glTexCoord3d",
    "glTexCoord3f",
    "glTexCoord3i",
    "glTexCoord3s",
    "glTexCoord4d",
    "glTexCoord4f",
    "glTexCoord4i",
    "glTexCoord4s",
    "glTexCoord1dv",
    "glTexCoord1fv",
    "glTexCoord1iv",
    "glTexCoord1sv",
    "glTexCoord2dv",
    "glTexCoord2fv",
    "glTexCoord2iv",
    "glTexCoord2sv",
    "glTexCoord3dv",
    "glTexCoord3fv",
    "glTexCoord3iv",
    "glTexCoord3sv",
    "glTexCoord4dv",
    "glTexCoord4fv",
    "glTexCoord4iv",
    "glTexCoord4sv",
    "glRasterPos2d",
    "glRasterPos2f",
    "glRasterPos2i",
    "glRasterPos2s",
    "glRasterPos3d",
    "glRasterPos3f",
    "glRasterPos3i",
    "glRasterPos3s",
    "glRasterPos4d",
    "glRasterPos4f",
    "glRasterPos4i",
    "glRasterPos4s",
    "glRasterPos2dv",
    "glRasterPos2fv",
    "glRasterPos2iv",
    "glRasterPos2sv",
    "glRasterPos3dv",
    "glRasterPos3fv",
    "glRasterPos3iv",
    "glRasterPos3sv",
    "glRasterPos4dv",
    "glRasterPos4fv",
    "glRasterPos4iv",
    "glRasterPos4sv",
    "glRectd",
    "glRectf",
    "glRecti",
    "glRects",
    "glRectdv",
    "glRectfv",
    "glRectiv",
    "glRectsv",
    "glVertexPointer",
    "glNormalPointer",
    "glColorPointer",
    "glIndexPointer",
    "glTexCoordPointer",
    "glEdgeFlagPointer",
    "glGetPointerv",
    "glArrayElement",
    "glDrawArrays",
    "glDrawElements",
    "glInterleavedArrays",
    "glShadeModel",
    "glLightf",
    "glLighti",
    "glLightfv",
    "glLightiv",
    "glGetLightfv",
    "glGetLightiv",
    "glLightModelf",
    "glLightModeli",
    "glLightModelfv",
    "glLightModeliv",
    "glMaterialf",
    "glMateriali",
    "glMaterialfv",
    "glMaterialiv",
    "glGetMaterialfv",
    "glGetMaterialiv",
    "glColorMaterial",
    "glPixelZoom",
    "glPixelTransferf",
    "glPixelTransferi",
    "glPixelMapfv",
    "glPixelMapuiv",
    "glPixelMapusv",
    "glGetPixelMapfv",
    "glGetPixelMapuiv",
    "glGetPixelMapusv",
    "glBitmap",
    "glCopyPixels",
    "glStencilFunc",
    "glStencilMask",
    "glStencilOp",
    "glClearStencil",
    "glTexGend",
    "glTexGenf",
    "glTexGeni",
    "glTexGendv",
    "glTexGenfv",
    "glTexGeniv",
    "glGetTexGendv",
    "glGetTexGenfv",
    "glGetTexGeniv",
    "glTexEnvfv",
    "glTexEnviv",
    "glGetTexEnvfv",
    "glGetTexEnviv",
    "glTexParameterfv",
    "glTexParameteriv",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    "glGetTexLevelParameterfv",
    "glGetTexLevelParameteriv",
    "glTexImage1D",
    "glGetTexImage",
    "glPrioritizeTextures",
    "glAreTexturesResident",
    "glIsTexture",
    "glTexSubImage1D",
    "glCopyTexImage1D",
    "glCopyTexImage2D",
    "glCopyTexSubImage1D",
    "glMap1d",
    "glMap1f",
    "glMap2d",
    "glMap2f",
    "glGetMapdv",
    "glGetMapfv",
    "glGetMapiv",
    "glEvalCoord1d",
    "glEvalCoord1f",
    "glEvalCoord1dv",
    "glEvalCoord1fv",
    "glEvalCoord2d",
    "glEvalCoord2f",
    "glEvalCoord2dv",
    "glEvalCoord2fv",
    "glMapGrid1d",
    "glMapGrid1f",
    "glMapGrid2d",
    "glMapGrid2f",
    "glEvalPoint1",
    "glEvalPoint2",
    "glEvalMesh1",
    "glEvalMesh2",
    "glFogf",
    "glFogi",
    "glFogfv",
    "glFogiv",
    "glFeedbackBuffer",
    "glPassThrough",
    "glSelectBuffer",
    "glInitNames",
    "glLoadName",
    "glPushName",
    "glPopName",
    "glDrawRangeElements",
    "glTexImage3D",
    "glTexSubImage3D",
    "glCopyTexSubImage3D",
    "glColorTable",
    "glColorSubTable",
    "glColorTableParameteriv",
    "glColorTableParameterfv",
    "glCopyColorSubTable",
    "glCopyColorTable",
    "glGetColorTable",
    "glGetColorTableParameterfv",
    "glGetColorTableParameteriv",
    "glBlendEquation",
    "glBlendColor",
    "glHistogram",
    "glResetHistogram",
    "glGetHistogram",
    "glGetHistogramParameterfv",
    "glGetHistogramParameteriv",
    "glMinmax",
    "glResetMinmax",
    "glGetMinmax",
    "glGetMinmaxParameterfv",
    "glGetMinmaxParameteriv",
    "glConvolutionFilter1D",
    "glConvolutionFilter2D",
    "glConvolutionParameterf",
    "glConvolutionParameterfv",
    "glConvolutionParameteri",
    "glConvolutionParameteriv",
    "glCopyConvolutionFilter1D",
    "glCopyConvolutionFilter2D",
    "glGetConvolutionFilter",
    "glGetConvolutionParameterfv",
    "glGetConvolutionParameteriv",
    "glSeparableFilter2D",
    "glGetSeparableFilter",
    "glActiveTexture",
    "glClientActiveTexture",
    "glCompressedTexImage1D",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage1D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    "glGetCompressedTexImage",
    "glMultiTexCoord1d",
    "glMultiTexCoord1dv",
    "glMultiTexCoord1f",
    "glMultiTexCoord1fv",
    "glMultiTexCoord1i",
    "glMultiTexCoord1iv",
    "glMultiTexCoord1s",
    "glMultiTexCoord1sv",
    "glMultiTexCoord2d",
    "glMultiTexCoord2dv",
    "glMultiTexCoord2f",
    "glMultiTexCoord2fv",
    "glMultiTexCoord2i",
    "glMultiTexCoord2iv",
    "glMultiTexCoord2s",
    "glMultiTexCoord2sv",
    "glMultiTexCoord3d",
    "glMultiTexCoord3dv",
    "glMultiTexCoord3f",
    "glMultiTexCoord3fv",
    "glMultiTexCoord3i",
    "glMultiTexCoord3iv",
    "glMultiTexCoord3s",
    "glMultiTexCoord3sv",
    "glMultiTexCoord4d",
    "glMultiTexCoord4dv",
    "glMultiTexCoord4f",
    "glMultiTexCoord4fv",
    "glMultiTexCoord4i",
    "glMultiTexCoord4iv",
    "glMultiTexCoord4s",
    "glMultiTexCoord4sv",
    "glLoadTransposeMatrixd",
    "glLoadTransposeMatrixf",
    "glMultTransposeMatrixd",
    "glMultTransposeMatrixf",
    "glSampleCoverage",
    "glActiveTextureARB",
    "glClientActiveTextureARB",
    "glMultiTexCoord1dARB",
    "glMultiTexCoord1dvARB",
    "glMultiTexCoord1fARB",
    "glMultiTexCoord1fvARB",
    "glMultiTexCoord1iARB",
    "glMultiTexCoord1ivARB",
    "glMultiTexCoord1sARB",
    "glMultiTexCoord1svARB",
    "glMultiTexCoord2dARB",
    "glMultiTexCoord2dvARB",
    "glMultiTexCoord2fARB",
    "glMultiTexCoord2fvARB",
    "glMultiTexCoord2iARB",
    "glMultiTexCoord2ivARB",
    "glMultiTexCoord2sARB",
    "glMultiTexCoord2svARB",
    "glMultiTexCoord3dARB",
    "glMultiTexCoord3dvARB",
    "glMultiTexCoord3fARB",
    "glMultiTexCoord3fvARB",
    "glMultiTexCoord3iARB",
    "glMultiTexCoord3ivARB",
    "glMultiTexCoord3sARB",
    "glMultiTexCoord3svARB",
    "glMultiTexCoord4dARB",
    "glMultiTexCoord4dvARB",
    "glMultiTexCoord4fARB",
    "glMultiTexCoord4fvARB",
    "glMultiTexCoord4iARB",
    "glMultiTexCoord4ivARB",
    "glMultiTexCoord4sARB",
    "glMultiTexCoord4svARB",
    "glBlendColorEXT",
    "glPolygonOffsetEXT",
    "glTexImage3DEXT",
    "glTexSubImage3DEXT",
    "glCopyTexSubImage3DEXT",
    "glGenTexturesEXT",
    "glDeleteTexturesEXT",
    "glBindTextureEXT",
    "glPrioritizeTexturesEXT",
    "glAreTexturesResidentEXT",
    "glIsTextureEXT",
    "glVertexPointerEXT",
    "glNormalPointerEXT",
    "glColorPointerEXT",
    "glIndexPointerEXT",
    "glTexCoordPointerEXT",
    "glEdgeFlagPointerEXT",
    "glGetPointervEXT",
    "glArrayElementEXT",
    "glDrawArraysEXT",
    "glBlendEquationEXT",
    "glPointParameterfEXT",
    "glPointParameterfvEXT",
    "glPointParameterfSGIS",
    "glPointParameterfvSGIS",
    "glColorTableEXT",
    "glColorSubTableEXT",
    "glGetColorTableEXT",
    "glGetColorTableParameterfvEXT",
    "glGetColorTableParameterivEXT",
    "glLockArraysEXT",
    "glUnlockArraysEXT",
    "glWindowPos2iMESA",
    "glWindowPos2sMESA",
    "glWindowPos2fMESA",
    "glWindowPos2dMESA",
    "glWindowPos2ivMESA",
    "glWindowPos2svMESA",
    "glWindowPos2fvMESA",
    "glWindowPos2dvMESA",
    "glWindowPos3iMESA",
    "glWindowPos3sMESA",
    "glWindowPos3fMESA",
    "glWindowPos3dMESA",
    "glWindowPos3ivMESA",
    "glWindowPos3svMESA",
    "glWindowPos3fvMESA",
    "glWindowPos3dvMESA",
    "glWindowPos4iMESA",
    "glWindowPos4sMESA",
    "glWindowPos4fMESA",
    "glWindowPos4dMESA",
    "glWindowPos4ivMESA",
    "glWindowPos4svMESA",
    "glWindowPos4fvMESA",
    "glWindowPos4dvMESA",
    "glResizeBuffersMESA",
    "glEnableTraceMESA",
    "glDisableTraceMESA",
    "glNewTraceMESA",
    "glEndTraceMESA",
    "glTraceAssertAttribMESA",
    "glTraceCommentMESA",
    "glTraceTextureMESA",
    "glTraceListMESA",
    "glTracePointerMESA",
    "glTracePointerRangeMESA",
    "glXCopyContext",
    "glXCreateGLXPixmap",
    "glXDestroyGLXPixmap",
    "glXUseXFont",
    "glXGetClientString",
    "glXQueryServerString",
    "glXQueryExtensionsString",
    "glXGetFBConfigs",
    "glXChooseFBConfig",
    "glXGetFBConfigAttrib",
    "glXGetVisualFromFBConfig",
    "glXCreateWindow",
    "glXDestroyWindow",
    "glXCreatePixmap",
    "glXDestroyPixmap",
    "glXCreatePbuffer",
    "glXDestroyPbuffer",
    "glXQueryDrawable",
    "glXCreateNewContext",
    "glXMakeContextCurrent",
    "glXGetCurrentReadDrawable",
    "glXGetCurrentDisplay",
    "glXQueryContext",
    "glXSelectEvent",
    "glXGetSelectedEvent",
    "glXGetContextIDEXT",
    "glXImportContextEXT",
    "glXFreeContextEXT",
    "glXQueryContextInfoEXT",
    "glXGetCurrentDisplayEXT",
};

void glClearIndex(GLfloat c)
{
    is1gl_stub(0);
}

void glIndexMask(GLuint mask)
{
    is1gl_stub(1);
}

void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    is1gl_stub(2);
}

void glAlphaFunc(GLenum func, GLclampf ref)
{
    is1gl_stub(3);
}

void glLogicOp(GLenum opcode)
{
    is1gl_stub(4);
}

void glCullFace(GLenum mode)
{
    is1gl_stub(5);
}

void glFrontFace(GLenum mode)
{
    is1gl_stub(6);
}

void glPointSize(GLfloat size)
{
    is1gl_stub(7);
}

void glLineStipple(GLint factor, GLushort pattern)
{
    is1gl_stub(8);
}

void glPolygonMode(GLenum face, GLenum mode)
{
    is1gl_stub(9);
}

void glPolygonOffset(GLfloat factor, GLfloat units)
{
    is1gl_stub(10);
}

void glPolygonStipple(const GLubyte * mask)
{
    is1gl_stub(11);
}

void glGetPolygonStipple(GLubyte * mask)
{
    is1gl_stub(12);
}

void glEdgeFlag(GLboolean flag)
{
    is1gl_stub(13);
}

void glEdgeFlagv(const GLboolean * flag)
{
    is1gl_stub(14);
}

void glGetClipPlane(GLenum plane, GLdouble * equation)
{
    is1gl_stub(15);
}

void glDrawBuffer(GLenum mode)
{
    is1gl_stub(16);
}

void glReadBuffer(GLenum mode)
{
    is1gl_stub(17);
}

GLboolean glIsEnabled(GLenum cap)
{
    is1gl_stub(18);
    return (GLboolean)0;
}

void glEnableClientState(GLenum cap)
{
    is1gl_stub(19);
}

void glDisableClientState(GLenum cap)
{
    is1gl_stub(20);
}

void glGetBooleanv(GLenum pname, GLboolean * params)
{
    is1gl_stub(21);
}

void glGetDoublev(GLenum pname, GLdouble * params)
{
    is1gl_stub(22);
}

GLint glRenderMode(GLenum mode)
{
    is1gl_stub(23);
    return (GLint)0;
}

void glHint(GLenum target, GLenum mode)
{
    is1gl_stub(24);
}

void glClearDepth(GLclampd depth)
{
    is1gl_stub(25);
}

void glDepthFunc(GLenum func)
{
    is1gl_stub(26);
}

void glDepthMask(GLboolean flag)
{
    is1gl_stub(27);
}

void glDepthRange(GLclampd near_val, GLclampd far_val)
{
    is1gl_stub(28);
}

void glClearAccum(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    is1gl_stub(29);
}

void glAccum(GLenum op, GLfloat value)
{
    is1gl_stub(30);
}

void glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
{
    is1gl_stub(31);
}

void glFrustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
{
    is1gl_stub(32);
}

void glLoadMatrixd(const GLdouble * m)
{
    is1gl_stub(33);
}

void glLoadMatrixf(const GLfloat * m)
{
    is1gl_stub(34);
}

void glScaled(GLdouble x, GLdouble y, GLdouble z)
{
    is1gl_stub(35);
}

GLboolean glIsList(GLuint list)
{
    is1gl_stub(36);
    return (GLboolean)0;
}

void glCallLists(GLsizei n, GLenum type, const GLvoid * lists)
{
    is1gl_stub(37);
}

void glListBase(GLuint base)
{
    is1gl_stub(38);
}

void glVertex2i(GLint x, GLint y)
{
    is1gl_stub(39);
}

void glVertex2s(GLshort x, GLshort y)
{
    is1gl_stub(40);
}

void glVertex3d(GLdouble x, GLdouble y, GLdouble z)
{
    is1gl_stub(41);
}

void glVertex3f(GLfloat x, GLfloat y, GLfloat z)
{
    is1gl_stub(42);
}

void glVertex3i(GLint x, GLint y, GLint z)
{
    is1gl_stub(43);
}

void glVertex3s(GLshort x, GLshort y, GLshort z)
{
    is1gl_stub(44);
}

void glVertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    is1gl_stub(45);
}

void glVertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    is1gl_stub(46);
}

void glVertex4i(GLint x, GLint y, GLint z, GLint w)
{
    is1gl_stub(47);
}

void glVertex4s(GLshort x, GLshort y, GLshort z, GLshort w)
{
    is1gl_stub(48);
}

void glVertex2dv(const GLdouble * v)
{
    is1gl_stub(49);
}

void glVertex2fv(const GLfloat * v)
{
    is1gl_stub(50);
}

void glVertex2iv(const GLint * v)
{
    is1gl_stub(51);
}

void glVertex2sv(const GLshort * v)
{
    is1gl_stub(52);
}

void glVertex3dv(const GLdouble * v)
{
    is1gl_stub(53);
}

void glVertex3fv(const GLfloat * v)
{
    is1gl_stub(54);
}

void glVertex3iv(const GLint * v)
{
    is1gl_stub(55);
}

void glVertex3sv(const GLshort * v)
{
    is1gl_stub(56);
}

void glVertex4dv(const GLdouble * v)
{
    is1gl_stub(57);
}

void glVertex4fv(const GLfloat * v)
{
    is1gl_stub(58);
}

void glVertex4iv(const GLint * v)
{
    is1gl_stub(59);
}

void glVertex4sv(const GLshort * v)
{
    is1gl_stub(60);
}

void glNormal3b(GLbyte nx, GLbyte ny, GLbyte nz)
{
    is1gl_stub(61);
}

void glNormal3d(GLdouble nx, GLdouble ny, GLdouble nz)
{
    is1gl_stub(62);
}

void glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
    is1gl_stub(63);
}

void glNormal3i(GLint nx, GLint ny, GLint nz)
{
    is1gl_stub(64);
}

void glNormal3s(GLshort nx, GLshort ny, GLshort nz)
{
    is1gl_stub(65);
}

void glNormal3bv(const GLbyte * v)
{
    is1gl_stub(66);
}

void glNormal3dv(const GLdouble * v)
{
    is1gl_stub(67);
}

void glNormal3fv(const GLfloat * v)
{
    is1gl_stub(68);
}

void glNormal3iv(const GLint * v)
{
    is1gl_stub(69);
}

void glNormal3sv(const GLshort * v)
{
    is1gl_stub(70);
}

void glIndexd(GLdouble c)
{
    is1gl_stub(71);
}

void glIndexf(GLfloat c)
{
    is1gl_stub(72);
}

void glIndexi(GLint c)
{
    is1gl_stub(73);
}

void glIndexs(GLshort c)
{
    is1gl_stub(74);
}

void glIndexub(GLubyte c)
{
    is1gl_stub(75);
}

void glIndexdv(const GLdouble * c)
{
    is1gl_stub(76);
}

void glIndexfv(const GLfloat * c)
{
    is1gl_stub(77);
}

void glIndexiv(const GLint * c)
{
    is1gl_stub(78);
}

void glIndexsv(const GLshort * c)
{
    is1gl_stub(79);
}

void glIndexubv(const GLubyte * c)
{
    is1gl_stub(80);
}

void glColor3b(GLbyte red, GLbyte green, GLbyte blue)
{
    is1gl_stub(81);
}

void glColor3d(GLdouble red, GLdouble green, GLdouble blue)
{
    is1gl_stub(82);
}

void glColor3f(GLfloat red, GLfloat green, GLfloat blue)
{
    is1gl_stub(83);
}

void glColor3i(GLint red, GLint green, GLint blue)
{
    is1gl_stub(84);
}

void glColor3s(GLshort red, GLshort green, GLshort blue)
{
    is1gl_stub(85);
}

void glColor3ub(GLubyte red, GLubyte green, GLubyte blue)
{
    is1gl_stub(86);
}

void glColor3ui(GLuint red, GLuint green, GLuint blue)
{
    is1gl_stub(87);
}

void glColor3us(GLushort red, GLushort green, GLushort blue)
{
    is1gl_stub(88);
}

void glColor4b(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
{
    is1gl_stub(89);
}

void glColor4d(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
{
    is1gl_stub(90);
}

void glColor4i(GLint red, GLint green, GLint blue, GLint alpha)
{
    is1gl_stub(91);
}

void glColor4s(GLshort red, GLshort green, GLshort blue, GLshort alpha)
{
    is1gl_stub(92);
}

void glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    is1gl_stub(93);
}

void glColor4ui(GLuint red, GLuint green, GLuint blue, GLuint alpha)
{
    is1gl_stub(94);
}

void glColor4us(GLushort red, GLushort green, GLushort blue, GLushort alpha)
{
    is1gl_stub(95);
}

void glColor3bv(const GLbyte * v)
{
    is1gl_stub(96);
}

void glColor3dv(const GLdouble * v)
{
    is1gl_stub(97);
}

void glColor3fv(const GLfloat * v)
{
    is1gl_stub(98);
}

void glColor3iv(const GLint * v)
{
    is1gl_stub(99);
}

void glColor3sv(const GLshort * v)
{
    is1gl_stub(100);
}

void glColor3ubv(const GLubyte * v)
{
    is1gl_stub(101);
}

void glColor3uiv(const GLuint * v)
{
    is1gl_stub(102);
}

void glColor3usv(const GLushort * v)
{
    is1gl_stub(103);
}

void glColor4bv(const GLbyte * v)
{
    is1gl_stub(104);
}

void glColor4dv(const GLdouble * v)
{
    is1gl_stub(105);
}

void glColor4fv(const GLfloat * v)
{
    is1gl_stub(106);
}

void glColor4iv(const GLint * v)
{
    is1gl_stub(107);
}

void glColor4sv(const GLshort * v)
{
    is1gl_stub(108);
}

void glColor4ubv(const GLubyte * v)
{
    is1gl_stub(109);
}

void glColor4uiv(const GLuint * v)
{
    is1gl_stub(110);
}

void glColor4usv(const GLushort * v)
{
    is1gl_stub(111);
}

void glTexCoord1d(GLdouble s)
{
    is1gl_stub(112);
}

void glTexCoord1f(GLfloat s)
{
    is1gl_stub(113);
}

void glTexCoord1i(GLint s)
{
    is1gl_stub(114);
}

void glTexCoord1s(GLshort s)
{
    is1gl_stub(115);
}

void glTexCoord2d(GLdouble s, GLdouble t)
{
    is1gl_stub(116);
}

void glTexCoord2i(GLint s, GLint t)
{
    is1gl_stub(117);
}

void glTexCoord2s(GLshort s, GLshort t)
{
    is1gl_stub(118);
}

void glTexCoord3d(GLdouble s, GLdouble t, GLdouble r)
{
    is1gl_stub(119);
}

void glTexCoord3f(GLfloat s, GLfloat t, GLfloat r)
{
    is1gl_stub(120);
}

void glTexCoord3i(GLint s, GLint t, GLint r)
{
    is1gl_stub(121);
}

void glTexCoord3s(GLshort s, GLshort t, GLshort r)
{
    is1gl_stub(122);
}

void glTexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    is1gl_stub(123);
}

void glTexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    is1gl_stub(124);
}

void glTexCoord4i(GLint s, GLint t, GLint r, GLint q)
{
    is1gl_stub(125);
}

void glTexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q)
{
    is1gl_stub(126);
}

void glTexCoord1dv(const GLdouble * v)
{
    is1gl_stub(127);
}

void glTexCoord1fv(const GLfloat * v)
{
    is1gl_stub(128);
}

void glTexCoord1iv(const GLint * v)
{
    is1gl_stub(129);
}

void glTexCoord1sv(const GLshort * v)
{
    is1gl_stub(130);
}

void glTexCoord2dv(const GLdouble * v)
{
    is1gl_stub(131);
}

void glTexCoord2fv(const GLfloat * v)
{
    is1gl_stub(132);
}

void glTexCoord2iv(const GLint * v)
{
    is1gl_stub(133);
}

void glTexCoord2sv(const GLshort * v)
{
    is1gl_stub(134);
}

void glTexCoord3dv(const GLdouble * v)
{
    is1gl_stub(135);
}

void glTexCoord3fv(const GLfloat * v)
{
    is1gl_stub(136);
}

void glTexCoord3iv(const GLint * v)
{
    is1gl_stub(137);
}

void glTexCoord3sv(const GLshort * v)
{
    is1gl_stub(138);
}

void glTexCoord4dv(const GLdouble * v)
{
    is1gl_stub(139);
}

void glTexCoord4fv(const GLfloat * v)
{
    is1gl_stub(140);
}

void glTexCoord4iv(const GLint * v)
{
    is1gl_stub(141);
}

void glTexCoord4sv(const GLshort * v)
{
    is1gl_stub(142);
}

void glRasterPos2d(GLdouble x, GLdouble y)
{
    is1gl_stub(143);
}

void glRasterPos2f(GLfloat x, GLfloat y)
{
    is1gl_stub(144);
}

void glRasterPos2i(GLint x, GLint y)
{
    is1gl_stub(145);
}

void glRasterPos2s(GLshort x, GLshort y)
{
    is1gl_stub(146);
}

void glRasterPos3d(GLdouble x, GLdouble y, GLdouble z)
{
    is1gl_stub(147);
}

void glRasterPos3f(GLfloat x, GLfloat y, GLfloat z)
{
    is1gl_stub(148);
}

void glRasterPos3i(GLint x, GLint y, GLint z)
{
    is1gl_stub(149);
}

void glRasterPos3s(GLshort x, GLshort y, GLshort z)
{
    is1gl_stub(150);
}

void glRasterPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    is1gl_stub(151);
}

void glRasterPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    is1gl_stub(152);
}

void glRasterPos4i(GLint x, GLint y, GLint z, GLint w)
{
    is1gl_stub(153);
}

void glRasterPos4s(GLshort x, GLshort y, GLshort z, GLshort w)
{
    is1gl_stub(154);
}

void glRasterPos2dv(const GLdouble * v)
{
    is1gl_stub(155);
}

void glRasterPos2fv(const GLfloat * v)
{
    is1gl_stub(156);
}

void glRasterPos2iv(const GLint * v)
{
    is1gl_stub(157);
}

void glRasterPos2sv(const GLshort * v)
{
    is1gl_stub(158);
}

void glRasterPos3dv(const GLdouble * v)
{
    is1gl_stub(159);
}

void glRasterPos3fv(const GLfloat * v)
{
    is1gl_stub(160);
}

void glRasterPos3iv(const GLint * v)
{
    is1gl_stub(161);
}

void glRasterPos3sv(const GLshort * v)
{
    is1gl_stub(162);
}

void glRasterPos4dv(const GLdouble * v)
{
    is1gl_stub(163);
}

void glRasterPos4fv(const GLfloat * v)
{
    is1gl_stub(164);
}

void glRasterPos4iv(const GLint * v)
{
    is1gl_stub(165);
}

void glRasterPos4sv(const GLshort * v)
{
    is1gl_stub(166);
}

void glRectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
{
    is1gl_stub(167);
}

void glRectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
{
    is1gl_stub(168);
}

void glRecti(GLint x1, GLint y1, GLint x2, GLint y2)
{
    is1gl_stub(169);
}

void glRects(GLshort x1, GLshort y1, GLshort x2, GLshort y2)
{
    is1gl_stub(170);
}

void glRectdv(const GLdouble * v1, const GLdouble * v2)
{
    is1gl_stub(171);
}

void glRectfv(const GLfloat * v1, const GLfloat * v2)
{
    is1gl_stub(172);
}

void glRectiv(const GLint * v1, const GLint * v2)
{
    is1gl_stub(173);
}

void glRectsv(const GLshort * v1, const GLshort * v2)
{
    is1gl_stub(174);
}

void glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(175);
}

void glNormalPointer(GLenum type, GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(176);
}

void glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(177);
}

void glIndexPointer(GLenum type, GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(178);
}

void glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(179);
}

void glEdgeFlagPointer(GLsizei stride, const GLvoid * ptr)
{
    is1gl_stub(180);
}

void glGetPointerv(GLenum pname, GLvoid ** params)
{
    is1gl_stub(181);
}

void glArrayElement(GLint i)
{
    is1gl_stub(182);
}

void glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
    is1gl_stub(183);
}

void glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
{
    is1gl_stub(184);
}

void glInterleavedArrays(GLenum format, GLsizei stride, const GLvoid * pointer)
{
    is1gl_stub(185);
}

void glShadeModel(GLenum mode)
{
    is1gl_stub(186);
}

void glLightf(GLenum light, GLenum pname, GLfloat param)
{
    is1gl_stub(187);
}

void glLighti(GLenum light, GLenum pname, GLint param)
{
    is1gl_stub(188);
}

void glLightfv(GLenum light, GLenum pname, const GLfloat * params)
{
    is1gl_stub(189);
}

void glLightiv(GLenum light, GLenum pname, const GLint * params)
{
    is1gl_stub(190);
}

void glGetLightfv(GLenum light, GLenum pname, GLfloat * params)
{
    is1gl_stub(191);
}

void glGetLightiv(GLenum light, GLenum pname, GLint * params)
{
    is1gl_stub(192);
}

void glLightModelf(GLenum pname, GLfloat param)
{
    is1gl_stub(193);
}

void glLightModeli(GLenum pname, GLint param)
{
    is1gl_stub(194);
}

void glLightModelfv(GLenum pname, const GLfloat * params)
{
    is1gl_stub(195);
}

void glLightModeliv(GLenum pname, const GLint * params)
{
    is1gl_stub(196);
}

void glMaterialf(GLenum face, GLenum pname, GLfloat param)
{
    is1gl_stub(197);
}

void glMateriali(GLenum face, GLenum pname, GLint param)
{
    is1gl_stub(198);
}

void glMaterialfv(GLenum face, GLenum pname, const GLfloat * params)
{
    is1gl_stub(199);
}

void glMaterialiv(GLenum face, GLenum pname, const GLint * params)
{
    is1gl_stub(200);
}

void glGetMaterialfv(GLenum face, GLenum pname, GLfloat * params)
{
    is1gl_stub(201);
}

void glGetMaterialiv(GLenum face, GLenum pname, GLint * params)
{
    is1gl_stub(202);
}

void glColorMaterial(GLenum face, GLenum mode)
{
    is1gl_stub(203);
}

void glPixelZoom(GLfloat xfactor, GLfloat yfactor)
{
    is1gl_stub(204);
}

void glPixelTransferf(GLenum pname, GLfloat param)
{
    is1gl_stub(205);
}

void glPixelTransferi(GLenum pname, GLint param)
{
    is1gl_stub(206);
}

void glPixelMapfv(GLenum map, GLint mapsize, const GLfloat * values)
{
    is1gl_stub(207);
}

void glPixelMapuiv(GLenum map, GLint mapsize, const GLuint * values)
{
    is1gl_stub(208);
}

void glPixelMapusv(GLenum map, GLint mapsize, const GLushort * values)
{
    is1gl_stub(209);
}

void glGetPixelMapfv(GLenum map, GLfloat * values)
{
    is1gl_stub(210);
}

void glGetPixelMapuiv(GLenum map, GLuint * values)
{
    is1gl_stub(211);
}

void glGetPixelMapusv(GLenum map, GLushort * values)
{
    is1gl_stub(212);
}

void glBitmap(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap)
{
    is1gl_stub(213);
}

void glCopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
{
    is1gl_stub(214);
}

void glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
    is1gl_stub(215);
}

void glStencilMask(GLuint mask)
{
    is1gl_stub(216);
}

void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
    is1gl_stub(217);
}

void glClearStencil(GLint s)
{
    is1gl_stub(218);
}

void glTexGend(GLenum coord, GLenum pname, GLdouble param)
{
    is1gl_stub(219);
}

void glTexGenf(GLenum coord, GLenum pname, GLfloat param)
{
    is1gl_stub(220);
}

void glTexGeni(GLenum coord, GLenum pname, GLint param)
{
    is1gl_stub(221);
}

void glTexGendv(GLenum coord, GLenum pname, const GLdouble * params)
{
    is1gl_stub(222);
}

void glTexGenfv(GLenum coord, GLenum pname, const GLfloat * params)
{
    is1gl_stub(223);
}

void glTexGeniv(GLenum coord, GLenum pname, const GLint * params)
{
    is1gl_stub(224);
}

void glGetTexGendv(GLenum coord, GLenum pname, GLdouble * params)
{
    is1gl_stub(225);
}

void glGetTexGenfv(GLenum coord, GLenum pname, GLfloat * params)
{
    is1gl_stub(226);
}

void glGetTexGeniv(GLenum coord, GLenum pname, GLint * params)
{
    is1gl_stub(227);
}

void glTexEnvfv(GLenum target, GLenum pname, const GLfloat * params)
{
    is1gl_stub(228);
}

void glTexEnviv(GLenum target, GLenum pname, const GLint * params)
{
    is1gl_stub(229);
}

void glGetTexEnvfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(230);
}

void glGetTexEnviv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(231);
}

void glTexParameterfv(GLenum target, GLenum pname, const GLfloat * params)
{
    is1gl_stub(232);
}

void glTexParameteriv(GLenum target, GLenum pname, const GLint * params)
{
    is1gl_stub(233);
}

void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(234);
}

void glGetTexParameteriv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(235);
}

void glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat * params)
{
    is1gl_stub(236);
}

void glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint * params)
{
    is1gl_stub(237);
}

void glTexImage1D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(238);
}

void glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
{
    is1gl_stub(239);
}

void glPrioritizeTextures(GLsizei n, const GLuint * textures, const GLclampf * priorities)
{
    is1gl_stub(240);
}

GLboolean glAreTexturesResident(GLsizei n, const GLuint * textures, GLboolean * residences)
{
    is1gl_stub(241);
    return (GLboolean)0;
}

GLboolean glIsTexture(GLuint texture)
{
    is1gl_stub(242);
    return (GLboolean)0;
}

void glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(243);
}

void glCopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
{
    is1gl_stub(244);
}

void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    is1gl_stub(245);
}

void glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
{
    is1gl_stub(246);
}

void glMap1d(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points)
{
    is1gl_stub(247);
}

void glMap1f(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points)
{
    is1gl_stub(248);
}

void glMap2d(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points)
{
    is1gl_stub(249);
}

void glMap2f(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points)
{
    is1gl_stub(250);
}

void glGetMapdv(GLenum target, GLenum query, GLdouble * v)
{
    is1gl_stub(251);
}

void glGetMapfv(GLenum target, GLenum query, GLfloat * v)
{
    is1gl_stub(252);
}

void glGetMapiv(GLenum target, GLenum query, GLint * v)
{
    is1gl_stub(253);
}

void glEvalCoord1d(GLdouble u)
{
    is1gl_stub(254);
}

void glEvalCoord1f(GLfloat u)
{
    is1gl_stub(255);
}

void glEvalCoord1dv(const GLdouble * u)
{
    is1gl_stub(256);
}

void glEvalCoord1fv(const GLfloat * u)
{
    is1gl_stub(257);
}

void glEvalCoord2d(GLdouble u, GLdouble v)
{
    is1gl_stub(258);
}

void glEvalCoord2f(GLfloat u, GLfloat v)
{
    is1gl_stub(259);
}

void glEvalCoord2dv(const GLdouble * u)
{
    is1gl_stub(260);
}

void glEvalCoord2fv(const GLfloat * u)
{
    is1gl_stub(261);
}

void glMapGrid1d(GLint un, GLdouble u1, GLdouble u2)
{
    is1gl_stub(262);
}

void glMapGrid1f(GLint un, GLfloat u1, GLfloat u2)
{
    is1gl_stub(263);
}

void glMapGrid2d(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
{
    is1gl_stub(264);
}

void glMapGrid2f(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
{
    is1gl_stub(265);
}

void glEvalPoint1(GLint i)
{
    is1gl_stub(266);
}

void glEvalPoint2(GLint i, GLint j)
{
    is1gl_stub(267);
}

void glEvalMesh1(GLenum mode, GLint i1, GLint i2)
{
    is1gl_stub(268);
}

void glEvalMesh2(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
{
    is1gl_stub(269);
}

void glFogf(GLenum pname, GLfloat param)
{
    is1gl_stub(270);
}

void glFogi(GLenum pname, GLint param)
{
    is1gl_stub(271);
}

void glFogfv(GLenum pname, const GLfloat * params)
{
    is1gl_stub(272);
}

void glFogiv(GLenum pname, const GLint * params)
{
    is1gl_stub(273);
}

void glFeedbackBuffer(GLsizei size, GLenum type, GLfloat * buffer)
{
    is1gl_stub(274);
}

void glPassThrough(GLfloat token)
{
    is1gl_stub(275);
}

void glSelectBuffer(GLsizei size, GLuint * buffer)
{
    is1gl_stub(276);
}

void glInitNames(void)
{
    is1gl_stub(277);
}

void glLoadName(GLuint name)
{
    is1gl_stub(278);
}

void glPushName(GLuint name)
{
    is1gl_stub(279);
}

void glPopName(void)
{
    is1gl_stub(280);
}

void glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices)
{
    is1gl_stub(281);
}

void glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(282);
}

void glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(283);
}

void glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    is1gl_stub(284);
}

void glColorTable(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table)
{
    is1gl_stub(285);
}

void glColorSubTable(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data)
{
    is1gl_stub(286);
}

void glColorTableParameteriv(GLenum target, GLenum pname, const GLint * params)
{
    is1gl_stub(287);
}

void glColorTableParameterfv(GLenum target, GLenum pname, const GLfloat * params)
{
    is1gl_stub(288);
}

void glCopyColorSubTable(GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
{
    is1gl_stub(289);
}

void glCopyColorTable(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    is1gl_stub(290);
}

void glGetColorTable(GLenum target, GLenum format, GLenum type, GLvoid * table)
{
    is1gl_stub(291);
}

void glGetColorTableParameterfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(292);
}

void glGetColorTableParameteriv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(293);
}

void glBlendEquation(GLenum mode)
{
    is1gl_stub(294);
}

void glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    is1gl_stub(295);
}

void glHistogram(GLenum target, GLsizei width, GLenum internalformat, GLboolean sink)
{
    is1gl_stub(296);
}

void glResetHistogram(GLenum target)
{
    is1gl_stub(297);
}

void glGetHistogram(GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
{
    is1gl_stub(298);
}

void glGetHistogramParameterfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(299);
}

void glGetHistogramParameteriv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(300);
}

void glMinmax(GLenum target, GLenum internalformat, GLboolean sink)
{
    is1gl_stub(301);
}

void glResetMinmax(GLenum target)
{
    is1gl_stub(302);
}

void glGetMinmax(GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid * values)
{
    is1gl_stub(303);
}

void glGetMinmaxParameterfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(304);
}

void glGetMinmaxParameteriv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(305);
}

void glConvolutionFilter1D(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * image)
{
    is1gl_stub(306);
}

void glConvolutionFilter2D(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * image)
{
    is1gl_stub(307);
}

void glConvolutionParameterf(GLenum target, GLenum pname, GLfloat params)
{
    is1gl_stub(308);
}

void glConvolutionParameterfv(GLenum target, GLenum pname, const GLfloat * params)
{
    is1gl_stub(309);
}

void glConvolutionParameteri(GLenum target, GLenum pname, GLint params)
{
    is1gl_stub(310);
}

void glConvolutionParameteriv(GLenum target, GLenum pname, const GLint * params)
{
    is1gl_stub(311);
}

void glCopyConvolutionFilter1D(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    is1gl_stub(312);
}

void glCopyConvolutionFilter2D(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height)
{
    is1gl_stub(313);
}

void glGetConvolutionFilter(GLenum target, GLenum format, GLenum type, GLvoid * image)
{
    is1gl_stub(314);
}

void glGetConvolutionParameterfv(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(315);
}

void glGetConvolutionParameteriv(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(316);
}

void glSeparableFilter2D(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * row, const GLvoid * column)
{
    is1gl_stub(317);
}

void glGetSeparableFilter(GLenum target, GLenum format, GLenum type, GLvoid * row, GLvoid * column, GLvoid * span)
{
    is1gl_stub(318);
}

void glActiveTexture(GLenum texture)
{
    is1gl_stub(319);
}

void glClientActiveTexture(GLenum texture)
{
    is1gl_stub(320);
}

void glCompressedTexImage1D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(321);
}

void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(322);
}

void glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(323);
}

void glCompressedTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(324);
}

void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(325);
}

void glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
{
    is1gl_stub(326);
}

void glGetCompressedTexImage(GLenum target, GLint lod, GLvoid * img)
{
    is1gl_stub(327);
}

void glMultiTexCoord1d(GLenum target, GLdouble s)
{
    is1gl_stub(328);
}

void glMultiTexCoord1dv(GLenum target, const GLdouble * v)
{
    is1gl_stub(329);
}

void glMultiTexCoord1f(GLenum target, GLfloat s)
{
    is1gl_stub(330);
}

void glMultiTexCoord1fv(GLenum target, const GLfloat * v)
{
    is1gl_stub(331);
}

void glMultiTexCoord1i(GLenum target, GLint s)
{
    is1gl_stub(332);
}

void glMultiTexCoord1iv(GLenum target, const GLint * v)
{
    is1gl_stub(333);
}

void glMultiTexCoord1s(GLenum target, GLshort s)
{
    is1gl_stub(334);
}

void glMultiTexCoord1sv(GLenum target, const GLshort * v)
{
    is1gl_stub(335);
}

void glMultiTexCoord2d(GLenum target, GLdouble s, GLdouble t)
{
    is1gl_stub(336);
}

void glMultiTexCoord2dv(GLenum target, const GLdouble * v)
{
    is1gl_stub(337);
}

void glMultiTexCoord2f(GLenum target, GLfloat s, GLfloat t)
{
    is1gl_stub(338);
}

void glMultiTexCoord2fv(GLenum target, const GLfloat * v)
{
    is1gl_stub(339);
}

void glMultiTexCoord2i(GLenum target, GLint s, GLint t)
{
    is1gl_stub(340);
}

void glMultiTexCoord2iv(GLenum target, const GLint * v)
{
    is1gl_stub(341);
}

void glMultiTexCoord2s(GLenum target, GLshort s, GLshort t)
{
    is1gl_stub(342);
}

void glMultiTexCoord2sv(GLenum target, const GLshort * v)
{
    is1gl_stub(343);
}

void glMultiTexCoord3d(GLenum target, GLdouble s, GLdouble t, GLdouble r)
{
    is1gl_stub(344);
}

void glMultiTexCoord3dv(GLenum target, const GLdouble * v)
{
    is1gl_stub(345);
}

void glMultiTexCoord3f(GLenum target, GLfloat s, GLfloat t, GLfloat r)
{
    is1gl_stub(346);
}

void glMultiTexCoord3fv(GLenum target, const GLfloat * v)
{
    is1gl_stub(347);
}

void glMultiTexCoord3i(GLenum target, GLint s, GLint t, GLint r)
{
    is1gl_stub(348);
}

void glMultiTexCoord3iv(GLenum target, const GLint * v)
{
    is1gl_stub(349);
}

void glMultiTexCoord3s(GLenum target, GLshort s, GLshort t, GLshort r)
{
    is1gl_stub(350);
}

void glMultiTexCoord3sv(GLenum target, const GLshort * v)
{
    is1gl_stub(351);
}

void glMultiTexCoord4d(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    is1gl_stub(352);
}

void glMultiTexCoord4dv(GLenum target, const GLdouble * v)
{
    is1gl_stub(353);
}

void glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    is1gl_stub(354);
}

void glMultiTexCoord4fv(GLenum target, const GLfloat * v)
{
    is1gl_stub(355);
}

void glMultiTexCoord4i(GLenum target, GLint s, GLint t, GLint r, GLint q)
{
    is1gl_stub(356);
}

void glMultiTexCoord4iv(GLenum target, const GLint * v)
{
    is1gl_stub(357);
}

void glMultiTexCoord4s(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
{
    is1gl_stub(358);
}

void glMultiTexCoord4sv(GLenum target, const GLshort * v)
{
    is1gl_stub(359);
}

void glLoadTransposeMatrixd(const GLdouble m[16])
{
    is1gl_stub(360);
}

void glLoadTransposeMatrixf(const GLfloat m[16])
{
    is1gl_stub(361);
}

void glMultTransposeMatrixd(const GLdouble m[16])
{
    is1gl_stub(362);
}

void glMultTransposeMatrixf(const GLfloat m[16])
{
    is1gl_stub(363);
}

void glSampleCoverage(GLclampf value, GLboolean invert)
{
    is1gl_stub(364);
}

void glActiveTextureARB(GLenum texture)
{
    is1gl_stub(365);
}

void glClientActiveTextureARB(GLenum texture)
{
    is1gl_stub(366);
}

void glMultiTexCoord1dARB(GLenum target, GLdouble s)
{
    is1gl_stub(367);
}

void glMultiTexCoord1dvARB(GLenum target, const GLdouble * v)
{
    is1gl_stub(368);
}

void glMultiTexCoord1fARB(GLenum target, GLfloat s)
{
    is1gl_stub(369);
}

void glMultiTexCoord1fvARB(GLenum target, const GLfloat * v)
{
    is1gl_stub(370);
}

void glMultiTexCoord1iARB(GLenum target, GLint s)
{
    is1gl_stub(371);
}

void glMultiTexCoord1ivARB(GLenum target, const GLint * v)
{
    is1gl_stub(372);
}

void glMultiTexCoord1sARB(GLenum target, GLshort s)
{
    is1gl_stub(373);
}

void glMultiTexCoord1svARB(GLenum target, const GLshort * v)
{
    is1gl_stub(374);
}

void glMultiTexCoord2dARB(GLenum target, GLdouble s, GLdouble t)
{
    is1gl_stub(375);
}

void glMultiTexCoord2dvARB(GLenum target, const GLdouble * v)
{
    is1gl_stub(376);
}

void glMultiTexCoord2fARB(GLenum target, GLfloat s, GLfloat t)
{
    is1gl_stub(377);
}

void glMultiTexCoord2fvARB(GLenum target, const GLfloat * v)
{
    is1gl_stub(378);
}

void glMultiTexCoord2iARB(GLenum target, GLint s, GLint t)
{
    is1gl_stub(379);
}

void glMultiTexCoord2ivARB(GLenum target, const GLint * v)
{
    is1gl_stub(380);
}

void glMultiTexCoord2sARB(GLenum target, GLshort s, GLshort t)
{
    is1gl_stub(381);
}

void glMultiTexCoord2svARB(GLenum target, const GLshort * v)
{
    is1gl_stub(382);
}

void glMultiTexCoord3dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r)
{
    is1gl_stub(383);
}

void glMultiTexCoord3dvARB(GLenum target, const GLdouble * v)
{
    is1gl_stub(384);
}

void glMultiTexCoord3fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r)
{
    is1gl_stub(385);
}

void glMultiTexCoord3fvARB(GLenum target, const GLfloat * v)
{
    is1gl_stub(386);
}

void glMultiTexCoord3iARB(GLenum target, GLint s, GLint t, GLint r)
{
    is1gl_stub(387);
}

void glMultiTexCoord3ivARB(GLenum target, const GLint * v)
{
    is1gl_stub(388);
}

void glMultiTexCoord3sARB(GLenum target, GLshort s, GLshort t, GLshort r)
{
    is1gl_stub(389);
}

void glMultiTexCoord3svARB(GLenum target, const GLshort * v)
{
    is1gl_stub(390);
}

void glMultiTexCoord4dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    is1gl_stub(391);
}

void glMultiTexCoord4dvARB(GLenum target, const GLdouble * v)
{
    is1gl_stub(392);
}

void glMultiTexCoord4fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    is1gl_stub(393);
}

void glMultiTexCoord4fvARB(GLenum target, const GLfloat * v)
{
    is1gl_stub(394);
}

void glMultiTexCoord4iARB(GLenum target, GLint s, GLint t, GLint r, GLint q)
{
    is1gl_stub(395);
}

void glMultiTexCoord4ivARB(GLenum target, const GLint * v)
{
    is1gl_stub(396);
}

void glMultiTexCoord4sARB(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
{
    is1gl_stub(397);
}

void glMultiTexCoord4svARB(GLenum target, const GLshort * v)
{
    is1gl_stub(398);
}

void glBlendColorEXT(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    is1gl_stub(399);
}

void glPolygonOffsetEXT(GLfloat factor, GLfloat bias)
{
    is1gl_stub(400);
}

void glTexImage3DEXT(GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(401);
}

void glTexSubImage3DEXT(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
{
    is1gl_stub(402);
}

void glCopyTexSubImage3DEXT(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    is1gl_stub(403);
}

void glGenTexturesEXT(GLsizei n, GLuint * textures)
{
    is1gl_stub(404);
}

void glDeleteTexturesEXT(GLsizei n, const GLuint * textures)
{
    is1gl_stub(405);
}

void glBindTextureEXT(GLenum target, GLuint texture)
{
    is1gl_stub(406);
}

void glPrioritizeTexturesEXT(GLsizei n, const GLuint * textures, const GLclampf * priorities)
{
    is1gl_stub(407);
}

GLboolean glAreTexturesResidentEXT(GLsizei n, const GLuint * textures, GLboolean * residences)
{
    is1gl_stub(408);
    return (GLboolean)0;
}

GLboolean glIsTextureEXT(GLuint texture)
{
    is1gl_stub(409);
    return (GLboolean)0;
}

void glVertexPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
{
    is1gl_stub(410);
}

void glNormalPointerEXT(GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
{
    is1gl_stub(411);
}

void glColorPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
{
    is1gl_stub(412);
}

void glIndexPointerEXT(GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
{
    is1gl_stub(413);
}

void glTexCoordPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
{
    is1gl_stub(414);
}

void glEdgeFlagPointerEXT(GLsizei stride, GLsizei count, const GLboolean * ptr)
{
    is1gl_stub(415);
}

void glGetPointervEXT(GLenum pname, GLvoid ** params)
{
    is1gl_stub(416);
}

void glArrayElementEXT(GLint i)
{
    is1gl_stub(417);
}

void glDrawArraysEXT(GLenum mode, GLint first, GLsizei count)
{
    is1gl_stub(418);
}

void glBlendEquationEXT(GLenum mode)
{
    is1gl_stub(419);
}

void glPointParameterfEXT(GLenum pname, GLfloat param)
{
    is1gl_stub(420);
}

void glPointParameterfvEXT(GLenum pname, const GLfloat * params)
{
    is1gl_stub(421);
}

void glPointParameterfSGIS(GLenum pname, GLfloat param)
{
    is1gl_stub(422);
}

void glPointParameterfvSGIS(GLenum pname, const GLfloat * params)
{
    is1gl_stub(423);
}

void glColorTableEXT(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table)
{
    is1gl_stub(424);
}

void glColorSubTableEXT(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data)
{
    is1gl_stub(425);
}

void glGetColorTableEXT(GLenum target, GLenum format, GLenum type, GLvoid * table)
{
    is1gl_stub(426);
}

void glGetColorTableParameterfvEXT(GLenum target, GLenum pname, GLfloat * params)
{
    is1gl_stub(427);
}

void glGetColorTableParameterivEXT(GLenum target, GLenum pname, GLint * params)
{
    is1gl_stub(428);
}

void glLockArraysEXT(GLint first, GLsizei count)
{
    is1gl_stub(429);
}

void glUnlockArraysEXT(void)
{
    is1gl_stub(430);
}

void glWindowPos2iMESA(GLint x, GLint y)
{
    is1gl_stub(431);
}

void glWindowPos2sMESA(GLshort x, GLshort y)
{
    is1gl_stub(432);
}

void glWindowPos2fMESA(GLfloat x, GLfloat y)
{
    is1gl_stub(433);
}

void glWindowPos2dMESA(GLdouble x, GLdouble y)
{
    is1gl_stub(434);
}

void glWindowPos2ivMESA(const GLint * p)
{
    is1gl_stub(435);
}

void glWindowPos2svMESA(const GLshort * p)
{
    is1gl_stub(436);
}

void glWindowPos2fvMESA(const GLfloat * p)
{
    is1gl_stub(437);
}

void glWindowPos2dvMESA(const GLdouble * p)
{
    is1gl_stub(438);
}

void glWindowPos3iMESA(GLint x, GLint y, GLint z)
{
    is1gl_stub(439);
}

void glWindowPos3sMESA(GLshort x, GLshort y, GLshort z)
{
    is1gl_stub(440);
}

void glWindowPos3fMESA(GLfloat x, GLfloat y, GLfloat z)
{
    is1gl_stub(441);
}

void glWindowPos3dMESA(GLdouble x, GLdouble y, GLdouble z)
{
    is1gl_stub(442);
}

void glWindowPos3ivMESA(const GLint * p)
{
    is1gl_stub(443);
}

void glWindowPos3svMESA(const GLshort * p)
{
    is1gl_stub(444);
}

void glWindowPos3fvMESA(const GLfloat * p)
{
    is1gl_stub(445);
}

void glWindowPos3dvMESA(const GLdouble * p)
{
    is1gl_stub(446);
}

void glWindowPos4iMESA(GLint x, GLint y, GLint z, GLint w)
{
    is1gl_stub(447);
}

void glWindowPos4sMESA(GLshort x, GLshort y, GLshort z, GLshort w)
{
    is1gl_stub(448);
}

void glWindowPos4fMESA(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    is1gl_stub(449);
}

void glWindowPos4dMESA(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    is1gl_stub(450);
}

void glWindowPos4ivMESA(const GLint * p)
{
    is1gl_stub(451);
}

void glWindowPos4svMESA(const GLshort * p)
{
    is1gl_stub(452);
}

void glWindowPos4fvMESA(const GLfloat * p)
{
    is1gl_stub(453);
}

void glWindowPos4dvMESA(const GLdouble * p)
{
    is1gl_stub(454);
}

void glResizeBuffersMESA(void)
{
    is1gl_stub(455);
}

void glEnableTraceMESA(GLbitfield mask)
{
    is1gl_stub(456);
}

void glDisableTraceMESA(GLbitfield mask)
{
    is1gl_stub(457);
}

void glNewTraceMESA(GLbitfield mask, const GLubyte * traceName)
{
    is1gl_stub(458);
}

void glEndTraceMESA(void)
{
    is1gl_stub(459);
}

void glTraceAssertAttribMESA(GLbitfield attribMask)
{
    is1gl_stub(460);
}

void glTraceCommentMESA(const GLubyte * comment)
{
    is1gl_stub(461);
}

void glTraceTextureMESA(GLuint name, const GLubyte* comment)
{
    is1gl_stub(462);
}

void glTraceListMESA(GLuint name, const GLubyte* comment)
{
    is1gl_stub(463);
}

void glTracePointerMESA(GLvoid* pointer, const GLubyte* comment)
{
    is1gl_stub(464);
}

void glTracePointerRangeMESA(const GLvoid* first, const GLvoid* last, const GLubyte* comment)
{
    is1gl_stub(465);
}

void glXCopyContext(Display * dpy, GLXContext src, GLXContext dst, unsigned long mask)
{
    is1gl_stub(466);
}

GLXPixmap glXCreateGLXPixmap(Display * dpy, XVisualInfo * vis, Pixmap pixmap)
{
    is1gl_stub(467);
    return (GLXPixmap)0;
}

void glXDestroyGLXPixmap(Display * dpy, GLXPixmap pix)
{
    is1gl_stub(468);
}

void glXUseXFont(Font font, int first, int count, int listBase)
{
    is1gl_stub(469);
}

const char * glXGetClientString(Display * dpy, int name)
{
    is1gl_stub(470);
    return (const char *)0;
}

const char * glXQueryServerString(Display * dpy, int screen, int name)
{
    is1gl_stub(471);
    return (const char *)0;
}

const char * glXQueryExtensionsString(Display * dpy, int screen)
{
    is1gl_stub(472);
    return (const char *)0;
}

GLXFBConfig * glXGetFBConfigs(Display * dpy, int screen, int * nelements)
{
    is1gl_stub(473);
    return (GLXFBConfig *)0;
}

GLXFBConfig * glXChooseFBConfig(Display * dpy, int screen, const int * attrib_list, int * nelements)
{
    is1gl_stub(474);
    return (GLXFBConfig *)0;
}

int glXGetFBConfigAttrib(Display * dpy, GLXFBConfig config, int attribute, int * value)
{
    is1gl_stub(475);
    return (int)0;
}

XVisualInfo * glXGetVisualFromFBConfig(Display * dpy, GLXFBConfig config)
{
    is1gl_stub(476);
    return (XVisualInfo *)0;
}

GLXWindow glXCreateWindow(Display * dpy, GLXFBConfig config, Window win, const int * attrib_list)
{
    is1gl_stub(477);
    return (GLXWindow)0;
}

void glXDestroyWindow(Display * dpy, GLXWindow win)
{
    is1gl_stub(478);
}

GLXPixmap glXCreatePixmap(Display * dpy, GLXFBConfig config, Pixmap pixmap, const int * attrib_list)
{
    is1gl_stub(479);
    return (GLXPixmap)0;
}

void glXDestroyPixmap(Display * dpy, GLXPixmap pixmap)
{
    is1gl_stub(480);
}

GLXPbuffer glXCreatePbuffer(Display * dpy, GLXFBConfig config, const int * attrib_list)
{
    is1gl_stub(481);
    return (GLXPbuffer)0;
}

void glXDestroyPbuffer(Display * dpy, GLXPbuffer pbuf)
{
    is1gl_stub(482);
}

void glXQueryDrawable(Display * dpy, GLXDrawable draw, int attribute, unsigned int * value)
{
    is1gl_stub(483);
}

GLXContext glXCreateNewContext(Display * dpy, GLXFBConfig config, int render_type, GLXContext share_list, Bool direct)
{
    is1gl_stub(484);
    return (GLXContext)0;
}

Bool glXMakeContextCurrent(Display * display, GLXDrawable draw, GLXDrawable read, GLXContext ctx)
{
    is1gl_stub(485);
    return (Bool)0;
}

GLXDrawable glXGetCurrentReadDrawable(void)
{
    is1gl_stub(486);
    return (GLXDrawable)0;
}

Display * glXGetCurrentDisplay(void)
{
    is1gl_stub(487);
    return (Display *)0;
}

int glXQueryContext(Display * dpy, GLXContext ctx, int attribute, int * value)
{
    is1gl_stub(488);
    return (int)0;
}

void glXSelectEvent(Display * dpy, GLXDrawable draw, unsigned long event_mask)
{
    is1gl_stub(489);
}

void glXGetSelectedEvent(Display * dpy, GLXDrawable draw, unsigned long * event_mask)
{
    is1gl_stub(490);
}

GLXContextID glXGetContextIDEXT(const GLXContext ctx)
{
    is1gl_stub(491);
    return (GLXContextID)0;
}

GLXContext glXImportContextEXT(Display * dpy, GLXContextID contextID)
{
    is1gl_stub(492);
    return (GLXContext)0;
}

void glXFreeContextEXT(Display * dpy, GLXContext ctx)
{
    is1gl_stub(493);
}

int glXQueryContextInfoEXT(Display * dpy, GLXContext ctx, int attribute, int * value)
{
    is1gl_stub(494);
    return (int)0;
}

Display * glXGetCurrentDisplayEXT(void)
{
    is1gl_stub(495);
    return (Display *)0;
}

